version: '3.9'

# Root mode override - removes user mapping for all services
# Only used when RUN_AS_ROOT=true in .env
# WARNING: Running containers as root reduces security

services:
  archon-server:
    user: null

  archon-mcp:
    user: null

  archon-agents:
    user: null

  archon-frontend:
    user: null